routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CitasController;
use App\Http\Controllers\PacienteController;
use App\Http\Controllers\DatoController;
use App\Http\Controllers\MedicoController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('inde');
});
Route::resource('paciente',PacienteController::class);
Route::resource('dato',DatoController::class);
Route::get('dato/{id}', [DatoController::class,'create'])->name('dato.create');
Route::resource('medico',MedicoController::class);
Route::resource('citas',CitasController::class);

app/Medico.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;


/**
 * Class Medico
 *
 * @property $id
 * @property $nombre
 * @property $apellido
 * @property $edad
 * @property $telefono
 * @property $informacion
 * @property $especialidad
 * @property $email
 * @property $sala_id
 * @property $created_at
 * @property $updated_at
 *
 * @package App
 * @mixin \Illuminate\Database\Eloquent\Builder
 */
class Medico extends Model
{
    
    static $rules = [
		'nombre' => 'required',
		'apellido' => 'required',
		'edad' => 'required',
		'telefono' => 'required',
		'informacion' => 'required',
		'especialidad' => 'required',
		'email' => 'required',
    'sala_id' => 'required',
    ];

    protected $perPage = 20;

    /**
     * Attributes that should be mass-assignable.
     *
     * @var array
     */
    protected $fillable = ['nombre','apellido','edad','telefono','informacion','especialidad','email','sala_id'];

    public function sala()
    {
        return $this->belongsTo(Sala::class,'sala_id' , 'id');
    }


}

app/Models/Medico.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Medico extends Model
{
    use HasFactory;
    protected $fillable=[
        'nombre' ,
        'apellido',
        'edad' ,
        'telefono' ,
        'informacion' ,
        'especialidad',
        'email',
        'sala_id'
        ];
    
    public function sala()
    {
        return $this->belongsTo(Sala::class,'sala_id' , 'id');
    }
}

app/Http/Controllers/MedicoController.php
<?php

namespace App\Http\Controllers;

use App\Medico;
use Illuminate\Http\Request;
use App\Sala;

/**
 * Class MedicoController
 * @package App\Http\Controllers
 */
class MedicoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $medicos = Medico::paginate(10);

        return view('medico.index', compact('medicos'))
            ->with('i', (request()->input('page', 1) - 1) * $medicos->perPage());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $medico = new Medico();
        $salas = Sala::where('estado', 'si')->get();
        return view('medico.create', compact('medico', 'salas'));
    }
    

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        request()->validate(Medico::$rules);
    
        $medico = Medico::create($request->all());
    
        $salaId = $request->input('sala_id');
        Sala::where('id', $salaId)->update(['estado' => 'no']);
    
        return redirect()->route('medico.index')
            ->with('success', 'Médico creado exitosamente.');
    }
    

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $medico = Medico::find($id);

        return view('medico.show', compact('medico'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $medico = Medico::find($id);
        $salas = Sala::where('estado', 'si')->get();
        return view('medico.edit', compact('medico', 'salas'));
    }
    

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  Medico $medico
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Medico $medico)
    {
        // Valida los datos del formulario
        $request->validate(Medico::$rules);
    
        // Obtiene el ID de la sala seleccionada del formulario
        $salaId = $request->input('sala_id');
    
        // Actualiza la sala en función del ID seleccionado
        Sala::where('id', $salaId)->update(['estado' => 'no']);
    
        // Actualiza los demás datos del médico
        $medico->update($request->all());
        return redirect()->route('medico.index')->with('success', 'Médico actualizado exitosamente');
    }
    

    /**
     * @param int $id
     * @return \Illuminate\Http\RedirectResponse
     * @throws \Exception
     */
    public function destroy($id)
    {
        // Busca y elimina al médico
        $medico = Medico::find($id);
        $medico->delete();
    
        // Recupera el ID de la sala asociada al médico (si existe)
        $salaId = $medico->sala_id;
    
        // Si se encontró un ID de sala asociado, actualiza su estado a "si"
        if (!is_null($salaId)) {
            Sala::where('id', $salaId)->update(['estado' => 'si']);
        }
    
        return redirect()->route('medico.index')
            ->with('success', 'Médico eliminado exitosamente');
    }
    
}

resources/views/medico/create.blade.php
@extends('layouts.app')

@section('template_title')
    {{ __('Create') }} Medico
@endsection

@section('content')
    <section class="content container-fluid">
        <div class="row">
            <div class="col-md-12">

                @includeif('partials.errors')

                <div class="card card-default">
                    <div class="card-header">
                        <span class="card-title">{{ __('Crear') }} Medico</span>
                    </div>
                    <div class="card-body">
                        <form method="POST" action="{{ route('medico.store') }}"  role="form" enctype="multipart/form-data">
                            @csrf

                            @include('medico.form')

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/medico/edit.blade.php
@extends('layouts.app')

@section('template_title')
    {{ __('Update') }} Medico
@endsection

@section('content')
    <section class="content container-fluid">
        <div class="">
            <div class="col-md-12">

                @includeif('partials.errors')

                <div class="card card-default">
                    <div class="card-header">
                        <span class="card-title">{{ __('Actualizar') }} Medico</span>
                    </div>
                    <div class="card-body">
                        <form method="POST" action="{{ route('medico.update', $medico->id) }}"  role="form" enctype="multipart/form-data">
                            {{ method_field('PATCH') }}
                            @csrf

                            @include('medico.form')

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/medico/form.blade.php
<div class="box box-info padding-1">
    <div class="box-body">
        
        <div class="form-group">
            {{ Form::label('nombre') }}
            {{ Form::text('nombre', $medico->nombre, ['class' => 'form-control' . ($errors->has('nombre') ? ' is-invalid' : ''), 'placeholder' => 'Nombre']) }}
            {!! $errors->first('nombre', '<div class="invalid-feedback">:message</div>') !!}
        </div>
        <div class="form-group">
            {{ Form::label('apellido') }}
            {{ Form::text('apellido', $medico->apellido, ['class' => 'form-control' . ($errors->has('apellido') ? ' is-invalid' : ''), 'placeholder' => 'Apellido']) }}
            {!! $errors->first('apellido', '<div class="invalid-feedback">:message</div>') !!}
        </div>
        <div class="form-group">
            {{ Form::label('edad') }}
            {{ Form::text('edad', $medico->edad, ['class' => 'form-control' . ($errors->has('edad') ? ' is-invalid' : ''), 'placeholder' => 'Edad']) }}
            {!! $errors->first('edad', '<div class="invalid-feedback">:message</div>') !!}
        </div>
        <div class="form-group">
            {{ Form::label('telefono') }}
            {{ Form::text('telefono', $medico->telefono, ['class' => 'form-control' . ($errors->has('telefono') ? ' is-invalid' : ''), 'placeholder' => 'Telefono']) }}
            {!! $errors->first('telefono', '<div class="invalid-feedback">:message</div>') !!}
        </div>
        <div class="form-group">
            {{ Form::label('informacion') }}
            {{ Form::text('informacion', $medico->informacion, ['class' => 'form-control' . ($errors->has('informacion') ? ' is-invalid' : ''), 'placeholder' => 'Informacion']) }}
            {!! $errors->first('informacion', '<div class="invalid-feedback">:message</div>') !!}
        </div>
        <div class="form-group">
            {{ Form::label('especialidad') }}
            {{ Form::text('especialidad', $medico->especialidad, ['class' => 'form-control' . ($errors->has('especialidad') ? ' is-invalid' : ''), 'placeholder' => 'Especialidad']) }}
            {!! $errors->first('especialidad', '<div class="invalid-feedback">:message</div>') !!}
        </div>
        <div class="form-group">
            {{ Form::label('email') }}
            {{ Form::text('email', $medico->email, ['class' => 'form-control' . ($errors->has('email') ? ' is-invalid' : ''), 'placeholder' => 'Email']) }}
            {!! $errors->first('email', '<div class="invalid-feedback">:message</div>') !!}
        </div>
        <div class="form-group">
            {{ Form::label('sala', 'Sala') }}
            {{ Form::select('sala_id', $salas->pluck('nombre', 'id'), $medico->sala_id, ['class' => 'form-control' . ($errors->has('sala_id') ? ' is-invalid' : ''), 'placeholder' => 'Selecciona una sala']) }}
            {!! $errors->first('sala_id', '<div class="invalid-feedback">:message</div>') !!}
        </div>


    </div>
    <div class="box-footer mt20">
        <button type="submit" class="btn btn-primary">{{ __('Actualizar') }}</button>
    </div>
</div>

resources/views/medico/index.blade.php
@extends('layouts.app')

@section('template_title')
    Medico
@endsection
        <style>
            .pagination {
                display: flex;
                flex-direction: row;
                justify-content: center;
                align-items: center;
                margin-right: 10px;
            }

            ul.pagination > li {
                display: inline-block;
            }

            ul.pagination > li > a {
                margin-right: 10px;
            }

            ul.pagination > li > a span {
                margin-left: 5px;
            }
            .btn-primary{
                background: #283E61;;
                border: none;
                padding: .50em;
                width: 90px;
                height: 30px;
                margin: 0 auto;
                color: #fff;
                text-align: center;
                border-radius: 25px;

            }
        </style>


@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12">
                <div class="card">
                    <div class="card-header">
                        <div style="display: flex; justify-content: space-between; align-items: center;">

                            <span id="card_title">
                                {{ __('Medico') }}
                            </span>

                             <div class="float-right">
                                <a href="{{ route('medico.create') }}" class="btn btn-primary btn-sm float-right"  data-placement="left">
                                  {{ __('Crear Nuevo') }}
                                </a>
                              </div>
                        </div>
                    </div>
                    @if ($message = Session::get('success'))
                        <div class="alert alert-success">
                            <p>{{ $message }}</p>
                        </div>
                    @endif

                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-striped table-hover">
                                <thead class="thead">
                                    <tr>
                                        <th>No</th>
                                        
										<th>Nombre</th>
										<th>Apellido</th>
										<th>Edad</th>
										<th>Telefono</th>
										<th>Informacion</th>
										<th>Especialidad</th>
										<th>Email</th>
                                        <th>Sala</th>

                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($medicos as $medico)
                                        <tr>
                                            <td>{{ ++$i }}</td>
                                            
											<td>{{ $medico->nombre }}</td>
											<td>{{ $medico->apellido }}</td>
											<td>{{ $medico->edad }}</td>
											<td>{{ $medico->telefono }}</td>
											<td>{{ $medico->informacion }}</td>
											<td>{{ $medico->especialidad }}</td>
											<td>{{ $medico->email }}</td>
                                            <td>{{ $medico->sala->nombre }}</td>

                                            <td>
                                                <form action="{{ route('medico.destroy',$medico->id) }}" method="POST">
                                                    <a class="btn btn-sm btn-primary " href="{{ route('medico.show',$medico->id) }}"><i class="fa fa-fw fa-eye"></i> {{ __('Mostrar') }}</a>
                                                    <a class="btn btn-sm btn-success" href="{{ route('medico.edit',$medico->id) }}"><i class="fa fa-fw fa-edit"></i> {{ __('Editar') }}</a>
                                                    @csrf
                                                    @method('DELETE')
                                                    <button type="submit" class="btn btn-danger btn-sm"><i class="fa fa-fw fa-trash"></i> {{ __('Eliminar') }}</button>
                                                </form>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="pagination">
                        <ul class="pagination">
                        @if ($medicos->currentPage() > 1)
                        <li><a href="{{ $medicos->previousPageUrl() }}" class="btn-primary">&laquo; Anterior</a></li>
                        @endif

                        @for ($i = 1; $i <= $medicos->lastPage(); $i++)
                        <li class="{{ $i == $medicos->currentPage() ? 'active' : '' }}">
                            <a href="{{ $medicos->url($i) }}" class="btn-primary">{{ $i }}</a>
                        </li>
                        @endfor

                        @if ($medicos->hasMorePages())
                        <li><a href="{{ $medicos->nextPageUrl() }}" class="btn-primary">Siguiente &raquo;</a></li>
                        @endif
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
@endsection

resources/views/medico/show.blade.php
@extends('layouts.app')

@section('template_title')
    {{ $medico->name ?? "{{ __('Mostrar') Medico" }}
@endsection

@section('content')
    <section class="content container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <div class="float-left">
                            <span class="card-title">{{ __('Mostrar') }} Medico</span>
                        </div>
                        
                    </div>

                    <div class="card-body">
                        
                        <div class="form-group">
                            <strong>Nombre:</strong>
                            {{ $medico->nombre }}
                        </div>
                        <div class="form-group">
                            <strong>Apellido:</strong>
                            {{ $medico->apellido }}
                        </div>
                        <div class="form-group">
                            <strong>Edad:</strong>
                            {{ $medico->edad }}
                        </div>
                        <div class="form-group">
                            <strong>Telefono:</strong>
                            {{ $medico->telefono }}
                        </div>
                        <div class="form-group">
                            <strong>Informacion:</strong>
                            {{ $medico->informacion }}
                        </div>
                        <div class="form-group">
                            <strong>Especialidad:</strong>
                            {{ $medico->especialidad }}
                        </div>
                        <div class="form-group">
                            <strong>Email:</strong>
                            {{ $medico->email }}
                        </div>
                        <div class="form-group">
                            <strong>Sala:</strong>
                            {{ $medico->sala->nombre }}
                        </div>
                        <div class="float-right">
                            <a class="btn btn-primary" href="{{ route('medico.index') }}"> {{ __('Atras') }}</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection